// Make bead.gcode: OrcaSlicer-style scarf seam and Z contouring (Z anti-aliasing), written the way
// OrcaSlicer writes them (GCode.cpp): scarf start Z = lerp(z - h, z, r) with E x r, scarf end at full
// Z with E x (1 - r) over the start ramp; Z contouring Z = z + z_diff with E x (h + z_diff) / h.
const fs = require('fs');
const H = 0.2, W = 0.42, FIL = 1.75;
const A = H * (W - H * (1 - Math.PI / 4));                // OrcaSlicer's rounded-rectangle area
const EPM = A / (Math.PI * (FIL / 2) ** 2);               // filament per mm of line
const out = ['; generated by gen_bead.js', 'G90', 'M83', 'G28', 'M73 P0 R1'];
let x = 0, y = 0;
const ext = (nx, ny, z, ratio, f = 3000) => {
  const L = Math.hypot(nx - x, ny - y);
  out.push(`G1 X${nx.toFixed(3)} Y${ny.toFixed(3)} Z${z.toFixed(4)} E${(L * EPM * ratio).toFixed(5)} F${f}`);
  x = nx; y = ny;
};
const travel = (nx, ny, z) => { out.push(`G0 X${nx.toFixed(3)} Y${ny.toFixed(3)} Z${z.toFixed(3)} F12000`); x = nx; y = ny; };
const layer = (z) => out.push(';LAYER_CHANGE', `;Z:${z}`, `;HEIGHT:${H}`, `G1 Z${z} F600`);
// square loop corners, 40 mm sides, starting at (80,80)
const sq = [[120, 80], [120, 120], [80, 120], [80, 80]];
// layer 1: plain loop
layer(0.2); out.push(';TYPE:Outer wall'); travel(80, 80, 0.2);
for (const [px, py] of sq) ext(px, py, 0.2, 1);
// layer 2: scarf seam over the first 20 mm (1 mm steps), the rest of the loop, then the closing overlap
const z2 = 0.4, S = 20;
layer(z2); out.push(';TYPE:Outer wall'); travel(80, 80, z2 - H);
out.push('; scarf start');
for (let i = 1; i <= S; i++) { const r = i / S; ext(80 + i, 80, z2 - H + H * r, r); }
for (const [px, py] of sq) ext(px, py, z2, 1);
out.push('; scarf end');
for (let i = 1; i < S; i++) { const r = i / S; ext(80 + i, 80, z2, 1 - r); }
// layer 3: Z-contoured top surface lines, z_diff from 0 to -0.1 mm and back along each line
const z3 = 0.6;
layer(z3); out.push(';TYPE:Top surface');
for (let row = 0; row < 5; row++) {
  const yy = 85 + row * 0.37;
  travel(85, yy, z3);
  for (let i = 1; i <= 30; i++) {
    const zd = -0.1 * Math.sin(Math.PI * i / 30);
    ext(85 + i, yy, z3 + zd, (H + zd) / H, 1800);
  }
}
out.push('M73 P100 R0', '; filament_diameter = 1.75', '; nozzle_diameter = 0.4', '; layer_height = 0.2');
fs.writeFileSync(__dirname + '/bead.gcode', out.join('\n') + '\n');
console.log('bead.gcode', out.length, 'lines');
